import "the-new-css-reset/css/reset.css";
import type { Metadata } from "next";
import { DotGothic16 } from "next/font/google";
import "./globals.css";

const geistDotGothic16 = DotGothic16({
  variable: "--font-geist-dot-gothic-16",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Contents() {}

export function PageLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={geistDotGothic16.variable}>{children}</body>
    </html>
  );
}
