import type { Metadata } from "next";

import { PageLayout } from "@/design/layouts/page_layout";

export const metadata: Metadata = {
  title: "aaaaaaaaaaaaaaaaaaaaa",
  description: "Generated by create next app",
};

export default PageLayout;
