import type { Metadata } from "next";

import "../globals.css";

export const metadata: Metadata = {
  title: "aaaaaaaaaaaaaaaaaaaaa",
  description: "Generated by create next app",
};

export default function PageLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return children;
}
